# -*- coding: utf-8 -*-
"""linear_regre_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rv7CHashlSGXw5T3JAyIGQkCtvm1MERe

#### DESCLAIMER
#### this is not my own project. i create this for training and learning
#### suource https://www.kaggle.com/code/shubham47/linear-regression-salary-dataset
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pandas import Series, DataFrame
import io
from google.colab import files

"""#### import data"""

data = pd.read_csv("/content/Salary_Data.csv")

"""#### EDA"""

data.head()

data.info()

data.describe()

data.cov()

data.corr()

sns.pairplot(data)
plt.show()

"""#### find independent and dependent variable"""

ind = data.drop('Salary', axis = 1)  # independent variable
ind

dep = data.Salary  # dependent variable
dep

"""#### Splitting Data"""

from sklearn.model_selection import train_test_split

ind_train, ind_test, dep_train, dep_test = train_test_split(ind, dep, random_state=0, test_size=0.30)  # 70% train and 30% test

print(ind_train.shape)
print(ind_test.shape)

"""#### model fitting"""

from sklearn.linear_model import LinearRegression

LR = LinearRegression()

LR.fit(ind_train, dep_train)

LR.intercept_

LR.coef_

"""#### prediction"""

dep_pred = LR.predict(ind_test)

dep_pred

dep_test